# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "xen_blkfront" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f222513b-ded1-49fa-b591-20ce86a2fe7f";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "systemd-1";
      fsType = "autofs";
    };

  fileSystems."/data/media" =
    { device = "/dev/disk/by-uuid/1fe0c325-b915-4ab2-8525-ef8968e4f6bd";
      fsType = "btrfs";
      options = [ "subvol=media" ];
    };

  fileSystems."/data/share" =
    { device = "/dev/disk/by-uuid/1fe0c325-b915-4ab2-8525-ef8968e4f6bd";
      fsType = "btrfs";
      options = [ "subvol=share" ];
    };

  fileSystems."/data/appdata" =
    { device = "/dev/disk/by-uuid/1fe0c325-b915-4ab2-8525-ef8968e4f6bd";
      fsType = "btrfs";
      options = [ "subvol=appdata" ];
    };

  fileSystems."/mnt/media" =
    { device = "/dev/disk/by-uuid/1fe0c325-b915-4ab2-8525-ef8968e4f6bd";
      fsType = "btrfs";
    };

  fileSystems."/mnt/data" =
    { device = "/dev/disk/by-uuid/2d204434-bca6-4901-ba89-f720112c9dca";
      fsType = "btrfs";
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
